import { createClientFromRequest } from 'npm:@base44/sdk@0.8.31';

// Commits futures liquidity to DB after successful Solana transaction.
// Uses standard MongoDB hex IDs for database compatibility.

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const serviceRole = base44.asServiceRole;
    const user = await base44.auth.me();
    if (!user) {
      return Response.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const { signature, commit_data } = await req.json();

    if (!signature || !commit_data) {
      return Response.json({ error: 'Missing signature or commit_data' }, { status: 400 });
    }

    // Check if existing offer exists (same LP, same outcome) to avoid duplicates
    const existingOffers = await serviceRole.entities.BetOffer.filter({
      bet_id: commit_data.market_id,
      lp_wallet_address: commit_data.walletAddress,
      outcome_label: commit_data.outcome_label,
    });

    let offerId;
    if (existingOffers.length > 0) {
      const existingOffer = existingOffers[0];
      const newAmountUnmatched = (existingOffer.amount_unmatched || 0) + commit_data.amount;
      await serviceRole.entities.BetOffer.update(existingOffer.id, {
        amount_offered: (existingOffer.amount_offered || 0) + commit_data.amount,
        amount_unmatched: newAmountUnmatched,
        status: newAmountUnmatched <= 0.0001 ? 'fully_matched' : 'partially_matched',
      });
      offerId = existingOffer.id;
    } else {
      // Create BetOffer with standard hex ID (auto-generated by DB)
      const newOffer = await serviceRole.entities.BetOffer.create({
        bet_id: commit_data.market_id,
        match_id: commit_data.market_id,
        outcome: commit_data.outcome_label === '1st' ? 'a' : commit_data.outcome_label === '2nd' ? 'b' : 'draw',
        outcome_label: commit_data.outcome_label,
        amount_offered: commit_data.amount,
        amount_matched: 0,
        amount_unmatched: commit_data.amount,
        status: 'open',
        odds_at_creation: commit_data.odds,
        lp_wallet_address: commit_data.walletAddress,
        solana_position_pda: commit_data.solana_position_pda,
        solana_bet_pool_pda: commit_data.solana_bet_pool_pda,
      });
      offerId = newOffer.id;
    }

    // Update UserBet status to active (LP position) and link the real BetOffer ID
    await serviceRole.entities.UserBet.update(commit_data.userBetId, {
      status: 'active',
      offer_id: offerId,
      liquidity_deposited: commit_data.amount,
      liquidity_unmatched: commit_data.amount,
    });

    // Update FuturesMarket outcome pool and LP offer count
    const market = await serviceRole.entities.FuturesMarket.get(commit_data.market_id);
    if (market && market.outcomes) {
      const outcomeIdx = market.outcomes.findIndex(o => o.label === commit_data.outcome_label);
      if (outcomeIdx !== -1) {
        market.outcomes[outcomeIdx].pool = (market.outcomes[outcomeIdx].pool || 0) + commit_data.amount;
        market.outcomes[outcomeIdx].lp_offers = (market.outcomes[outcomeIdx].lp_offers || 0) + 1;
        market.total_volume = (market.total_volume || 0) + commit_data.amount;
        await serviceRole.entities.FuturesMarket.update(commit_data.market_id, {
          outcomes: market.outcomes,
          total_volume: market.total_volume,
        });
      }
    }

    return Response.json({ success: true, userBetId: commit_data.userBetId, offerId });
  } catch (error) {
    return Response.json({ error: error.message }, { status: 500 });
  }
});